### ISSUE TITLE
Upgrade to Django 4.2, OAf, Python 3.11

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-api-framework#12]
* [x] Django 4.2
  * [x] Open Zaak https://github.com/open-zaak/open-zaak/issues/1597
  * [x] Open Notifications https://github.com/open-zaak/open-notificaties/issues/124
  * [x] Objects API https://github.com/maykinmedia/objects-api/pull/362
  * [x] Objecttypes https://github.com/maykinmedia/objects-api/issues/385
  * [x] Open Klant https://github.com/maykinmedia/open-klant/pull/169

* [x] Open API framework
  * [x] Open Zaak https://github.com/open-zaak/open-zaak/pull/1667
  * [x] Open Notifications https://github.com/open-zaak/open-notificaties/pull/160
  * [x] Objects API: https://github.com/maykinmedia/objects-api/pull/358
  * [x] Objecttypes: https://github.com/maykinmedia/objecttypes-api/pull/93
  * [x] Open Klant: https://github.com/maykinmedia/open-klant/pull/176

* [x] Python 3.11
  * [x] Open Zaak https://github.com/open-zaak/open-zaak/pull/1701
  * [x] Open Notifications https://github.com/open-zaak/open-notificaties/pull/164
  * [x] Objects API https://github.com/maykinmedia/objects-api/pull/380
  * [x] Objecttypes https://github.com/maykinmedia/objecttypes-api/pull/117
  * [x] Open Klant https://github.com/maykinmedia/open-klant/pull/184
